### ISSUE TITLE
remove nested table headers?

### ISSUE THREAD

**Issue by MayaGans** [glin/reactable#102]
Hi! Firstly thank you so much for this wonderful package!! I was curious if there was a way to remove the headers in nested tables? I tried leveraging the css of the class "inner-table" but this didn't quite work. Any ideas/tips appreciated! Thank you again!

```
data <- unique(CO2[, c("Plant", "Type")])

reactable(data, details = function(index) {
  plant_data <- CO2[CO2$Plant == data$Plant[index], ]
  htmltools::div(style = "padding: 16px",
    reactable(plant_data, outlined = TRUE, class = "inner-table")
  )
})
```

**Comment by MayaGans** [comment]
Ah! I can just set display: none! Of course this works right when I bother you 🤦

**Comment by glin** [comment]
Hi, there's no built-in way remove column headers, but you can do it with CSS as you've found. I would recommend hiding the headers off-screen rather than using `display: none` though, for better accessibility: https://www.accessibility-developer-guide.com/examples/tables/hidden-headers/

Here's an example of how to do that in R Markdown:

````r
```{r}
library(reactable)

reactable(
  CO2,
  bordered = TRUE,
  # Visually hide column headers
  class = "hidden-column-headers",
  # Prevent hidden column headers from being tabbed/focused
  sortable = FALSE
)
```
````

````css
```{css}
/* Visually hide column headers, but keep them accessible to screen reader users. */
.hidden-column-headers .rt-thead {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
```
````

Unfortunately, there's no documented way to style the table head or header row right now, so I used the internal `.rt-thead` selector here. Undocumented CSS classes are subject to change, but `.rt-thead` is probably stable enough to use for now.

I also disabled sorting to prevent the hidden headers from being tabbed to and sorted, which could be confusing.

Since this relies on undocumented CSS, there might be a built-in way to hide headers in the future. Or maybe table header rows could be made themeable. Headless tables are at least common enough that a few table libraries out there have it built in as an option.
