### ISSUE TITLE
Separators in footer, danish currency.

### ISSUE THREAD

**Issue by MagnusUdvikler** [glin/reactable#115]
Hi,

I hope that you could help me figuring out how to format the footer with separators as in the column. More specifically i want the footer to show the the total separated in thousands by "." and decimals by "," so that total looks something like "9.173.700,00 kr." (danish currency)

My code is the following 

reactable(Liste, pagination= FALSE, striped = TRUE, highlight = TRUE, searchable = TRUE,
          columns = list(
          `Instrument Name` = colDef(name = "Selskabsnavn"),
          `ISIN` = colDef(footer = "Børsnoterede aktier i alt"),
          `Market Value` = colDef(name = "Markedsværdi, kr.", footer =JS("function(colInfo) {
        var total = 0
        colInfo.data.forEach(function(row) {
          total += row[colInfo.column.id]
        })
        return '$' + total.toFixed(2)
      }"), format = colFormat(currency = "DKK", separators = TRUE, locales = "da-DK", digits = 4)
                                  )
          ),
  defaultColDef = colDef(footerStyle = list(fontWeight = "bold"))
  )

Best regards
Magnus

**Comment by glin** [comment]
Hi, column formatters don't apply to footers because footers are just arbitrary content, so you'll have to format the footer manually. If you want to use a JavaScript function for the footer, I'd recommend using [`Number.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) to do the currency formatting.

For example, you can open up a browser JavaScript console and run this:
```js
(9173700).toLocaleString('da-DK', { style: 'currency', currency: 'DKK' })
// "9.173.700,00 kr."
```

Here's an example based on an example from the docs (sorry, I couldn't run your example):

```r
library(dplyr)
library(htmltools)

data <- MASS::Cars93[18:47, ] %>%
  mutate(Price = Price * 10000) %>%
  select(Manufacturer, Model, Type, Sales = Price)

reactable(
  data,
  searchable = TRUE,
  defaultPageSize = 5,
  minRows = 5,
  columns = list(
    Manufacturer = colDef(footer = "Total"),
    Sales = colDef(
      footer = JS("function(colInfo) {
        var total = 0
        colInfo.data.forEach(function(row) {
          total += row[colInfo.column.id]
        })
        return total.toLocaleString('da-DK', { style: 'currency', currency: 'DKK' })
      }")
    )
  ),
  defaultColDef = colDef(footerStyle = list(fontWeight = "bold"))
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/105614392-be0a0900-5d8e-11eb-8e03-9fb309725978.png)

**Comment by MagnusUdvikler** [comment]
Thx this worked perfectly:)
