### ISSUE TITLE
Ability to rename filenames for the browser

### ISSUE THREAD

**Issue by strboul** [glin/reactable#119]
I mainly use reactable on the console to inspect the data.frames I work with. Since I open many tables to inspect in many different tabs, it would be great to be able to name them (currently everything is shown as `index.html`).

For example:
```r
reactable::reactable(mtcars, filename = "mtcars")
```

If this suggestion makes sense, I can also send a PR.

Love the reactable :heart: thanks for developing it.

**Comment by glin** [comment]
I think the filename of a widget is typically controlled by its print method. `htmlwidgets:::print.htmlwidget()` calls `htmltools::html_print()` underneath, which hardcodes `index.html` as the filename:
```r
> htmltools::html_print
function (html, background = "white", viewer = getOption("viewer", 
    utils::browseURL)) 
{
    www_dir <- tempfile("viewhtml")
    dir.create(www_dir)
    index_html <- file.path(www_dir, "index.html")
    save_html(html, file = index_html, background = background, 
        libdir = "lib")
    if (!is.null(viewer)) 
        viewer(index_html)
    invisible(index_html)
}
```

Since that's not configurable, how about creating a custom wrapper for reactable that adds a `<title>` tag? Something like this:
```r
reactable2 <- function(..., title = "reactable") {
  htmltools::browsable(
    htmltools::tagList(
      htmltools::tags$head(
        htmltools::tags$title(title)
      ),
      reactable::reactable(...)
    )
  )
}

reactable2(mtcars, title = "mtcars table")
```
The filename would still be index.html, but at least browser tabs would show the title instead.

Or to actually change the filename, you could create a custom print method where the filename is configurable:
```r
# Custom print method for reactable, adapted from htmlwidgets:::print.htmlwidget
# and htmltools::html_print. Uses the elementId as default filename if present.
print.reactable <- function(x, ..., filename = NULL) {
  if (is.null(filename)) {
    filename <- paste0(if (!is.null(x$elementId)) x$elementId else "reactable", ".html")
  }
  www_dir <- tempfile("viewhtml")
  dir.create(www_dir)
  file <- file.path(www_dir, filename)
  html <- htmltools::as.tags(x, standalone = TRUE)
  htmltools::save_html(html, file = file)
  utils::browseURL(file)
  invisible(html)
}

reactable(mtcars, elementId = "mtcars-tbl")
```
A downside with the custom print method is that the browser tab is still really long if you're viewing from RStudio - it's something like `http://localhost:25817/session/viewhtml1c385255566f/mtcars-tbl.html`

**Comment by strboul** [comment]
> The filename would still be index.html, but at least browser tabs would show the title instead.

The table solution looks good, that's what I looked for. Thanks!
