### ISSUE TITLE
Colour cells based on cell indices, not cell values

### ISSUE THREAD

**Issue by mattwarkentin** [glin/reactable#160]
Hi @glin,

Is there a straightforward way to add a fill colour to cells based on a cells location/index, rather than the actual value of the cell? For example, my table happens to be square, and I would like to colour the "lower triangle" or "upper triangle" or "diagonal"...and well I can't really think of how I would do that.

Is this possible?

Thanks for your help.

**Comment by glin** [comment]
Yes for the row index, but the column index might be tricky. The conditional styling functions give you direct access to the row index (2nd argument of R functions and `rowInfo.index` for JS functions): https://glin.github.io/reactable/articles/conditional-styling.html#cell-styling. But they only have the column name/ID, not the index, so you'd need some way to map column name to column index. If your table can be sorted, you may also need to use a JS function to get the relative row index from `rowInfo.viewIndex`.

Here's a quick example of styling based on the relative row index and column index. This puts a gray background on the first row of the table (even after sorting) and even columns. To get the column index, I hardcoded an ordered list of column names in the function.

```r
library(reactable)

data <- as.data.frame(volcano[1:5, 1:5])

reactable(
  data,
  defaultColDef = colDef(
    style = JS("function(rowInfo, colInfo) {
      // Get the relative row index (this starts at zero in JavaScript, so you can add 1)
      const rowIndex = rowInfo.viewIndex + 1

      // Get the column index. This isn't available anywhere, so figure it out
      // based on the column name.
      const columns = ['V1', 'V2', 'V3', 'V4', 'V5']
      const colIndex = columns.indexOf(colInfo.id) + 1

      // Background color for cells in the first row
      if (rowIndex === 1) {
        return { background: 'hsl(0, 0%, 95%)' }
      }

      // Background color for cells in even columns
      if (colIndex % 2 === 0) {
        return { background: 'hsl(0, 0%, 95%)' }
      }
    }")
  )
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/120086505-23efff80-c0a5-11eb-9265-067522e5f755.png)

Since you mentioned triangles and diagonals, a background image on the table body could also work if you just want colors over general areas of the table. For example, using a CSS gradient to color the top-right triangle with a transparent light blue, and the bottom-left triangle of the table with a transparent light orange:

```r
library(reactable)

data <- as.data.frame(volcano[1:5, 1:5])

reactable(
  data,
  theme = reactableTheme(
    tableBodyStyle = list(
      background = "linear-gradient(to left bottom, rgba(0, 255, 255, .17) 50%, rgba(238, 222, 170, .20) 50%)"
    )
  )
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/120086605-c90ad800-c0a5-11eb-947c-59d751d41d3d.png)

If a background image works, you can tweak the position and colors in the linear gradient CSS, https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient()#values.

**Comment by algo-se** [comment]
Couldn´t you map `const columns = ['V1', 'V2', 'V3', 'V4', 'V5']` from `rowInfo.row `?
