### ISSUE TITLE
Table not responsive to editor content width

### ISSUE THREAD

**Issue by systemnova** [glin/reactable#163]
Within Rstudio global options i've set th editor content width to 1600px for RMarkdown within my notebook.
The container the table sits in never fills the width even with fullWidth = TRUE.

Is it possible to change the table to fill the full 1600px of the editor?

**Comment by glin** [comment]
Thanks for the report. This is now fixed in the development version on GitHub (https://github.com/glin/reactable/commit/b888c395f94a793d339696db9a7e1364f6e07596):

> * Tables are now displayed with full width when rendered inside an R Markdown document or R Notebook ([#163](https://github.com/glin/reactable/issues/163)).

Previously, reactable used the default sizing behavior for HTML widgets in R Notebooks, which was something like a max width of 800px. This default behavior is now disabled.

Here are before/after screenshots for comparison:

**Before**
![Current version of reactable printed in an R Markdown document with limited width](https://user-images.githubusercontent.com/20401866/121788455-0c2f7580-cb93-11eb-80d3-ccafa25a9bf5.png)

**After**
![Fixed version of reactable printed in an R Markdown document that stretches to full width](https://user-images.githubusercontent.com/20401866/121788478-25382680-cb93-11eb-8e52-cd187bc27332.png)
