### ISSUE TITLE
Slow rendering with sparklines

### ISSUE THREAD

**Issue by matthias-a** [glin/reactable#17]
Hi there and thanks a lot for this package! 
I tried to create a table with sparklines, similar to your [example](https://glin.github.io/reactable/articles/examples.html#embedding-html-widgets), but for a data set with a little more entries (~5,000 rows). Here, the rendering of the table gets very slow. Refer to the following code snippet:
```R
library(reactable)
library(sparkline)

dat <- data.frame(
  a = rnorm(5000), 
  b = rnorm(5000), 
  c = rnorm(5000),
  spark = NA
)

reactable(
  data = dat,
  columns = list(
    spark = colDef(cell = function(value, index) {
      sparkline(as.numeric(dat[index, c("a", "b", "c")]))
    })
  )
)
```
Maybe I just use it in a wrong way or did not read well enough the documentation, but is there a way, that the rendering of the sparklines is done in a kind of lazy manner, e.g. when a new page is loaded? Same slow rendering happens when instead of sparklines, row details with plots are used. Do you have any idea? Thanks in advance!

**Comment by glin** [comment]
With R render functions, all the content has to be generated upfront since the table is purely client-side and can't run R code on the fly. If server-side rendering is added in the future, then those sparklines could potentially be rendered lazily within a Shiny app.

So for now, if you want to render custom content lazily, you'll have to use a JavaScript render function (check out the [custom rendering](https://glin.github.io/reactable/articles/custom-rendering.html) doc for a couple more details).

There's an example of rendering sparklines in JS here, which you might be able to adapt, although it uses a different library for sparklines: https://github.com/glin/reactable/issues/5#issuecomment-513570900

**Comment by matthias-a** [comment]
Thanks for your answer, the references are helpful!

**Comment by klmr** [comment]
@glin I’m having a similar issue (providing custom `cell` functions that generate HTML tags causes *massive* — >100x — slowdown) so I noted your comment with interest. Unfortunately I don’t think “server-side” mode would solve this particular issue: I’ve just tried running the same code with `server = TRUE`, and rather than improving performance it slowed it down by another factor 1.5–2.

For reference, here’s some code to reproduce this (this MWE uses simple `cell` functions that could be trivially ported to JavaScript, but the problem also exists with more complex functions that are hard to convert):

```r
prettify = TRUE  # Unsetting this makes loading >100x faster.

library(shiny)
library(reactable)


rep = 10000L

dataset = data.frame(
  User = rep(Sys.getenv('USER'), rep),
  Login = Sys.time() + stats::rnorm(rep, sd = 100000),
  Status = sample(c('Active', 'Inactive', 'Paused', 'Gone'), rep, replace = TRUE),
  Command = rep('Rscript --no-save -e "print(1 + 1)"', rep)
)

ui = bootstrapPage(reactableOutput('table'))

server = function (input, output) {
  output$table = renderReactable(
    timeit(
      reactable(
        dataset,
        columns = if (prettify) {
          list(
            User = colDef(cell = \(x) tags$code(x)),
            Login = colDef(cell = \(x) tags$span(strftime(x, '%Y-%m-%d %H:%M'), title = x)),
            Status = colDef(cell = format_status),
            Command = colDef(cell = \(x) tags$code(x))
          )
        },
        server = TRUE
      )
    )
  )
}

format_status = function (x) {
  c(Active = '✅', Inactive = '❌', Paused = '⏸️', Gone = '🚫')[[x]]
}

timeit = function (expr) {
  on.exit(print(structure(proc.time() - start_time, class = 'proc_time')))
  start_time = proc.time()
  expr
}

shiny::shinyApp(ui, server)
```

```r
> packageVersion('reactable')
[1] ‘0.4.4.9001’
> packageVersion('V8')
[1] ‘6.0.2’
> version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts               
```

**Comment by klmr** [comment]
(Ah: I found the follow-up comments on the issue #22 and saw that you’ve already addressed that.)
