### ISSUE TITLE
pagination = FALSE does not work with groupBy

### ISSUE THREAD

**Issue by algo-se** [glin/reactable#201]
Hi, I think this has not been reported yet, otherwise please ignore this.

There is a minor bug when using `groupBy` that prevents `pagination` from working correctly.

```
library(reactable)

reactable(iris,
          pagination = FALSE)
```

![image](https://user-images.githubusercontent.com/72490678/135831836-f7128516-3967-4930-b90e-c6ce3cb58841.png)
```
library(reactable)

reactable(iris,
          groupBy = "Species",
          pagination = FALSE)
```

![image](https://user-images.githubusercontent.com/72490678/135831951-4e12a40a-b3f6-4e07-bd3e-5c2e8d040f99.png)

Edit: Right now I´m using 
```
    removeUI(
      selector = ".rt-pagination-nav"
    )
```
as a workaround.

**Comment by glin** [comment]
Fixed in https://github.com/glin/reactable/commit/e5d3d1df16342f18e47b734e6b01cc446b575900 and https://github.com/glin/reactable/commit/f406c62624eccaef277a66c361862f4c4a04a671 (related to https://github.com/glin/reactable/issues/214), thanks again. There were two separate issues in the dev version that were fixed:
- `pagination = FALSE` now actually disables pagination for grouped tables
- Auto-shown pagination now works for grouped tables again (like it did for the reactable 0.2.3), so the pagination should be automatically hidden for `reactable(iris, groupBy = "Species")` again.
