### ISSUE TITLE
Search does not work for hidden columns

### ISSUE THREAD

**Issue by shahreyar-abeer** [glin/reactable#217]
Searching does not include columns with `colDef(show = FALSE)`

```r
library(reactable)
library(magrittr)

iris %>%
  reactable::reactable(searchable = TRUE, columns = list(Species = colDef(show = T)))

```
Yields the following:

![image](https://user-images.githubusercontent.com/20732893/146159049-ded739f1-f475-4c7f-b1b3-b9e94433796b.png)

And 

```r
library(reactable)
library(magrittr)

iris %>%
  reactable::reactable(searchable = TRUE, columns = list(Species = colDef(show = F)))

```
Yields:

![image](https://user-images.githubusercontent.com/20732893/146159158-3dda2674-7b97-48b5-b6a3-f5e8a775f46c.png)

**Comment by daeyoonlee** [comment]
I think it is correct that invisible columns are not searched. Allowing this can confuse users.

**Comment by shahreyar-abeer** [comment]
I understand that this may not be standard, I'm looking for a way to implement this actually.

**Comment by lukr90** [comment]
one workaround would be to render empty cells:
```
    iris %>% reactable(searchable = TRUE, 
                       columns = list(Species = colDef(name = "", sortable = F, cell = function(){""})))
```

**Comment by glin** [comment]
Hi, this is intentional and won't be changed, but I get that it can be useful in some cases. I implemented some custom filters that work on hidden columns in the [Popular Movies demo](https://glin.github.io/reactable/articles/popular-movies/popular-movies.html). It uses Crosstalk to do the custom filtering completely outside reactable. There's no specific example of a search field that works on hidden columns, but there are similar filters that could be used as a starting point.

Besides Crosstalk, the [`Reactable.setFilter()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-setfilter) method in the new JavaScript API could be used to filter a hidden column:
```r
library(reactable)
library(magrittr)

htmltools::browsable(
  tagList(
    div(
      style = "margin-bottom: 12px",
      tags$input(
        type = "text",
        placeholder = "Search by species",
        style = "padding: 4px 8px; width: 100%",
        oninput = "Reactable.setFilter('iris-table', 'Species', this.value)"
      )
    ),
    
    iris %>%
      reactable::reactable(
        columns = list(Species = colDef(show = F)),
        elementId = "iris-table"
      )
  )
)
```
The drawback is that it only filters a single column, however.

If there's enough demand for searching to work on hidden columns, it could possibly be added to reactable as a toggleable option (maybe in the JavaScript API). But I'm not a huge fan of enabling it by default because of the UX issues. If a search filter applies to a hidden column, I think that information should be visible somewhere in the table, like the genre column in the Popular Movies example.

**Comment by shahreyar-abeer** [comment]
Thanks a lot for your comment!
This should work for now I guess.

**Comment by glin** [comment]
> If there's enough demand for searching to work on hidden columns, it could possibly be added to reactable as a toggleable option

Following up on this, it's now possible to enable searching on hidden columns using a new `colDef(searchable = TRUE)` argument in the dev version (https://github.com/glin/reactable/commit/ab5b55b82a40365643248c8c02d6d875cf0b396e). The main reason for adding the `searchable` arg was to disable searching on certain columns, but it was a natural extension to also have it enable searching on hidden columns.

> * `colDef()` gains a `searchable` argument to enable or disable global table searching. Columns can be excluded from searching using `colDef(searchable = FALSE)`, and hidden columns can be included in searching using `colDef(searchable = TRUE)` ([#217](https://github.com/glin/reactable/issues/217)).

Here's an example of this:
```r
library(reactable)

reactable(
  iris,
  searchable = TRUE,
  columns = list(Species = colDef(show = FALSE, searchable = TRUE))
)
```
