### ISSUE TITLE
All columns to left of a colGroup are sticky 

### ISSUE THREAD

**Issue by chrisumphlett** [glin/reactable#236]
I have 3 columns that I want to be sticky on the left, then some columns I don't want to be sticky, then some column groups. When I defined the column groups, the columns between the sticky ones, and the groups, are now all sticking.

In this gif, I'm only starting with the 3rd sticky column because the first 2 have personal information. This shows the column groups removed from the definition of the table (the 5 columns with no column header). Everything works as it should. 
![no column group](https://user-images.githubusercontent.com/7210482/163612636-a45c2cef-74e7-43d4-9279-db4bab65460b.gif)

In this gif, I have added the column groups back, and you can see that there are more sticky columns to the right of `Lead Score`.
![yes column group](https://user-images.githubusercontent.com/7210482/163614449-5e919c3a-0349-4161-b558-c0e210675922.gif)

**Comment by chrisumphlett** [comment]
There's also an issue with using `rowStyle` with column groups. I use the code below to produce a line to separate each email domain group in the table. The border does not appear on the columns to the left of the column groups.

```
rowStyle = JS("
                          function(rowInfo, state) {
                            // Ignore padding rows
                            if (!rowInfo) return
                      
                            // Add horizontal separators between groups when sorting by school
                            const firstSorted = state.sorted[0]
                            if (firstSorted && firstSorted.id === 'Email Domain') {
                              const nextRow = state.pageRows[rowInfo.viewIndex + 1]
                              if (nextRow && rowInfo.row['Email Domain'] !== nextRow['Email Domain']) {
                                // Use box-shadow to add a 1px border without taking extra space
                                return { boxShadow: 'inset 0 -1px 0 rgb(0, 0, 0)' }
                              }
                            }
                          }
                        ")
```

![image](https://user-images.githubusercontent.com/7210482/163868662-0cdf6791-249a-41e4-9afa-e1b9c72e5c52.png)

**Comment by glin** [comment]
Can you post minimal, runnable example code? I think I get the first question, but the second one is a little more confusing for me.

For the first question, I bet it's an unfortunate interaction between two behaviors with column groups and sticky columns:

- When a table has column groups, any columns that weren't explicitly added to a `colGroup()` still need a column group for it to be a valid HTML table. reactable combines adjacent "ungrouped" columns into their own, unnamed column group so you don't get unwanted borders.
- If a sticky column is in a column group, all columns in the group will automatically be made sticky, including the column group header, so you don't end up with visual brokenness.

Since the Lead Score column was one of those columns without an explicit `colGroup()`, it ended up being grouped with all the other "ungrouped" columns, so the stickiness stuck all those "ungrouped" columns.

To fix this, you can create an explicit `colGroup()` with just the Lead Score column in it. It doesn't have to be named either:
```r
colGroup(name = "", columns = "Lead Score")
```

I'm not sure what reactable could do to make this better. Maybe split out ungrouped sticky columns into their own implicit column group so it doesn't bring along all the other ungrouped columns. That could be complicated and create other issues for sticky columns/column groups though.

At least for now, we could definitely improve the documentation and call this out as a caveat.

**Comment by chrisumphlett** [comment]
Your suggested workaround is a great solution for the sticky column issue.

Implementing this changes the second issue a bit, and I think it's less confusing now-- originally it was exacerbated by the first problem. The border extends through the column groups now, but stops at the sticky columns. I can make an example if necessary but I don't think it will be to understand the issue.

![image](https://user-images.githubusercontent.com/7210482/165294601-cf055aff-6fc2-4e1e-9a9d-dd29934832d4.png)

**Comment by chrisumphlett** [comment]
I could also make this a new issue, it's not related to column groups at all, it's an issue with sticky columns

**Comment by glin** [comment]
I see the issue with row borders and sticky columns now. The problem is a styling clash between the opaque `background-color` on the sticky column cells and the `box-shadow` borders applied to the rows. The box shadows on the rows are getting hidden by the solid white backgrounds on the sticky cells. Usually, this isn't a problem because cells have a transparent background by default, but sticky cells need a solid background to prevent visual overlapping content when scrolling horizontally.

Here's a reproducible example based on the [Borders between groups of data](https://glin.github.io/reactable/articles/cookbook/cookbook.html#borders-between-groups-of-data) example from the Demo Cookbook. It's the same example, but with a sticky `Painter` column.

```r
library(dplyr)

data <- as_tibble(MASS::painters, rownames = "Painter") %>%
  filter(School %in% c("A", "B", "C")) %>%
  mutate(School = recode(School, A = "Renaissance", B = "Mannerist", C = "Seicento")) %>%
  select(Painter, School, everything()) %>%
  group_by(School) %>%
  slice(1:3)

reactable(
  data,
  defaultSorted = list(School = "asc", Drawing = "desc"),
  borderless = TRUE,
  columns = list(Painter = colDef(sticky = "left")),
  rowStyle = JS("
    function(rowInfo, state) {
      // Ignore padding rows
      if (!rowInfo) return

      // Add horizontal separators between groups when sorting by school
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'School') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row['School'] !== nextRow['School']) {
          // Use box-shadow to add a 2px border without taking extra space
          return { boxShadow: 'inset 0 -2px 0 rgba(0, 0, 0, 0.1)' }
        }
      }
    }
  ")
)
```

I don't see a way to work around this in the sticky column styles without breaking things, but the example code could work around this in a few ways.

One workaround would be to use `border` instead of `box-shadow` for the border styles. True borders don't get hidden unlike the pseudo-borders with the box shadows. The only other difference is that borders cause layout shifts, so you'll probably want invisible placeholder borders to prevent the shifting:
```r
reactable(
  data,
  defaultSorted = list(School = "asc", Drawing = "desc"),
  borderless = TRUE,
  columns = list(Painter = colDef(sticky = "left")),
  rowStyle = JS("
    function(rowInfo, state) {
      // Ignore padding rows
      if (!rowInfo) return

      // Add horizontal separators between groups when sorting by school
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'School') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row['School'] !== nextRow['School']) {
          return { borderBottom: '2px solid rgba(0, 0, 0, 0.1)' }
        }
      }

      // Add invisible borders to prevent layout shifting
      return { borderBottom: '2px solid transparent' }
    }
  ")
)
```

Another workaround would be to move the box shadow styles from `rowStyle` to the cell styles. The background color on the cells cover up the box shadows on the rows because the rows are behind the cells. This option is a little less flexible though, if you have existing styles on your cells.
```r
reactable(
  data,
  defaultSorted = list(School = "asc", Drawing = "desc"),
  borderless = TRUE,
  columns = list(Painter = colDef(sticky = "left")),
  defaultColDef = colDef(style = JS("
    function(rowInfo, colInfo, state) {
      // Ignore padding rows
      if (!rowInfo) return

      // Add horizontal separators between groups when sorting by school
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'School') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row['School'] !== nextRow['School']) {
          // Use box-shadow to add a 2px border without taking extra space
          return { boxShadow: 'inset 0 -2px 0 rgba(0, 0, 0, 0.1)' }
        }
      }
    }
  "))
)
```
