### ISSUE TITLE
Save_reactable not working 

### ISSUE THREAD

**Issue by SaraPerrins** [glin/reactable#264]
Hi Glin, 
This package is amazing. Thanks for your tremendous work on this. I am getting errors related to save_reactable. 
<img width="337" alt="Screen Shot 2022-08-10 at 4 54 38 PM" src="https://user-images.githubusercontent.com/107080563/184042514-26e61939-eb33-4b65-a35a-1f03329e8e71.png">
 
I've also tried the full (input, output) call but still get the error: 
<img width="513" alt="Screen Shot 2022-08-10 at 4 57 17 PM" src="https://user-images.githubusercontent.com/107080563/184042776-967e2897-cb09-4293-9640-72f51dd6227e.png">

Thanks for help with this.

**Comment by glin** [comment]
Hi, [`save_reactable()`](https://kcuilla.github.io/reactablefmtr/reference/save_reactable.html) comes from the reactablefmtr package. If you don't have that package installed or loaded, you'll need to do that first. If you do have reactablefmtr loaded, then it may be this bug that was fixed in the development version of reactablefmtr: 

> https://kcuilla.github.io/reactablefmtr/news/index.html#bug-fixes-2-1-0
> Bug Fixes
> Fixed [save_reactable()](https://kcuilla.github.io/reactablefmtr/reference/save_reactable.html) function to display as [save_reactable()](https://kcuilla.github.io/reactablefmtr/reference/save_reactable.html) and not save_reactable_test()

If so, then you could either use `reactablefmtr::save_reactable_test()` for now, or install the development version to get the fix.

**Comment by SaraPerrins** [comment]
Thanks glin. 
`reactablefmtr::save_reactable_test()` worked, but the image it saves is cropped. In the case of very wide tables, is there a way to save the entire table?
