### ISSUE TITLE
FYI: new major react-table release 

### ISSUE THREAD

**Issue by dpastoor** [glin/reactable#35]
Not too sure how if this will make a difference for how reactable is maintained etc

v7.0 out: https://github.com/tannerlinsley/react-table/releases

details:

React Table v7 marks the culmination of over a years worth of work to refactor the entire library to a hooks-only UI/Style/Markup agnostic table building utility.

This latest version is a collection of React hooks and plugins (which are also hooks!) that help you flexibly compose logical features of the most complex data grids into a single API returned by the primary useTable hook. This API is performant, extensible, and unopinionated about markup, styles or rendering.

From the new Concepts documentation page:
React Table v7 is a headless utility, which means out of the box, it doesn't render or supply any actual UI elements. You are in charge of utilizing the state and callbacks of the hooks provided by this library to render your own table markup. Read this article to understand why React Table is built this way. If you don't want to, then here's a quick rundown anyway:

Separation of Concerns - Not that superficial kind you read about all the time. The real kind. React Table as a library honestly has no business being in charge of your UI. The look, feel, and overall experience of your table is what makes your app or product great. The less React Table gets in the way of that, the better!
Maintenance - By removing the massive (and seemingly endless) API surface area required to support every UI use-case, React Table can remain small, easy-to-use and simple to update/maintain.
Extensibility - UI presents countless edge cases for a library simply because it's a creative medium, and one where every developer does things differently. By not dictating UI concerns, React Table empowers the developer to design and extend the UI based on their unique use-case.

**Comment by glin** [comment]
Thanks for the heads-up. The plan is to eventually migrate to v7, but it probably won't happen for a while. v7 is so different that there's not really a straightforward migration path, and it'll take some work to convert everything over. But once that happens, v7 should make it much easier to add custom features, including some that would've been very difficult or impossible to do with v6.

In the meantime, this won't make a difference to how reactable is maintained or developed. react-table v6 is still a great library to work with, and fairly stable. If v6 does have any more bug fixes or updates, I'll make sure to pull them into reactable.

**Comment by glin** [comment]
The migration to React Table v7 is done (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). It was a pretty large rewrite of the JS component, but worth it in the end for the greater flexibility and maintainability. 

Here were the changes from the migration alone, copied from NEWS. Most of these would've been hard or near impossible to do in v6 without a significant fork.


### New features

* Column group headers can now be resized.
* Column group headers and filters are now sticky. Previously, only column  headers were sticky ([#107](https://github.com/glin/reactable/issues/107)).
* Expanded rows now stay expanded on sorting, filtering, and pagination changes.  Previously, expanded rows were always collapsed on sorting and pagination  changes, and incorrectly persisted on filtering changes  ([#39](https://github.com/glin/reactable/issues/39)).
* The row selection column is now always placed as the first column in the  table, even before the `groupBy` and row details columns  ([#71](https://github.com/glin/reactable/issues/71)).
* Aggregated rows can now be selected when multiple selection is enabled.
* JavaScript render functions and style functions receive several new properties:
  * `rowInfo.expanded` and `cellInfo.expanded` indicating whether the row is expanded
  * `cellInfo.selected` property indicating whether the cell's row is selected
  * `state.page`, `state.pageSize`, and `state.pages` for the current page index,
    page size, and number of pages in the table
* JavaScript render functions for cells, headers, footers, and row details  can now access the table state using a new `state` argument  ([#88](https://github.com/glin/reactable/issues/88)).
* Custom cell click actions can now access the table state using a new `state`  argument.

### Breaking changes

* When expanding grouped rows, sub rows are now paginated and included in the  row count.
* When both `columnGroups` and `groupBy` arguments are provided, `groupBy`  columns are no longer added to a column group automatically  ([#87](https://github.com/glin/reactable/issues/87)).
* The `defaultGroupHeader` argument in `reactableLang()` is now deprecated and  no longer used. Use the `columnGroups` argument in `reactable()` to customize  the column group header for `groupBy` columns.
* The `state.expanded` property has been removed from JavaScript render  functions and style functions. To check whether a row is expanded, use  `rowInfo.expanded` instead.
* The `rowInfo.page` and `cellInfo.page` properties have been removed from  JavaScript render functions and style functions. To get the current page  index of the table, use `state.page` instead.

### Minor improvements and bug fixes

* Column resizing is now limited by the min and max width of the column.
* Column group headers and filter cells in fixed height tables now display  properly in Safari, Chrome, and the RStudio Viewer
  ([#76](https://github.com/glin/reactable/issues/76)).
* In `reactable()`, `defaultExpanded = TRUE` now expands all rows in the table,  not just rows on the first page.
* In `reactable()`, `defaultExpanded = TRUE` now works when column groups are present.
* Aggregated cell values are now recalculated when filtering or searching the table.
* Aggregate functions now always take the unaggregated values in the column.  Previously, if there were multiple `groupBy` columns, aggregate functions  could take aggregated values which could produce inaccurate calculations  (e.g., when calculating the mean of values).* Searching now properly ignores the row details and selection columns.
* Increased the width of the row selection column to match the row details column.
* Selected rows now reset when the table data changes in Shiny  ([#110](https://github.com/glin/reactable/issues/110)).
* When selecting rows, errors from other Crosstalk widgets no longer cause the  table to disappear.
* Row group expander buttons are now labeled as "Expand group" and  "Collapse group" instead of "Expand details" and  "Collapse details". Use the  new `groupExpandLabel` and `groupCollapseLabel` arguments in `reactableLang()`  to customize the accessible labels for row group expander buttons.
* Row name cells are now marked up as row headers for assistive technologies.
