### ISSUE TITLE
Collapsable rows

### ISSUE THREAD

**Issue by nergiszaim** [glin/reactable#39]
When a sorting is done in expanded rows the rows goes back to collapse mode. Is there a way to avoid this?

**Comment by glin** [comment]
There isn't right now, but it may be possible in the future. I've looked into this before, and found that it was tricky to do because React Table only keeps track of expanded rows on the current page. 

That means if you expand the 3rd row and sort the table, the 3rd row on the page would still be sorted, even though the row order is completely different. To keep the actual expanded row open would require some fighting around with library internals, so I've just put it off for now. But this is something I really want as well, so it may happen sooner than later.

**Comment by glin** [comment]
This is now fixed in the development version (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). Expanded rows should stay expanded on any sorting, filtering, and pagination changes.
