### ISSUE TITLE
Shiny: .selection=colDef(show=FALSE) not working with columnGroups

### ISSUE THREAD

**Issue by petbrueck** [glin/reactable#52]
Hi,
Thanks for this great package! 
I stumbled over the following issue: 

Hiding the selection column using ".selection=colDef(show=FALSE)" is not working if I also create columnGroups. 

```
library(shiny)
library(reactable)

ui <- fluidPage(
  reactableOutput("withoutcolumnGroups", height="600px"),
  reactableOutput("withcolumnGroups", height="600px")
  )

server <- function(input, output) {
   output$withoutcolumnGroups <- renderReactable({ 
   reactable( iris ,
              onClick="select",
              selection="single",
              columns=list(
                .selection = colDef(show=FALSE)
              )
   )
 })

 output$withcolumnGroups <- renderReactable({ 
   reactable( iris ,
              onClick="select",
              selection="single",
              columns=list(
                .selection = colDef(show=FALSE)
              ),
            columnGroups = list(
              colGroup(name = "ColumnGroup Header", 
                       columns = c("Petal.Length", "Petal.Width") 
              )
            ) 
   )
 })
}

shinyApp(ui = ui, server = server)
```
Is there any way to avoid this? Thanks in advance!

**Comment by glin** [comment]
Thanks for reporting this. This was a bug that should now be fixed in the development version (https://github.com/glin/reactable/commit/4abe2d09b89b885cffbcf524ee98dbd31ffeccb0). The problem was that there was an extra, empty column being added when using row selection + column groups. That extra column was what `.selection = colDef(show = FALSE)` was being applied to here.

It's more visibly obvious with a bordered style:
```r
library(reactable)

reactable(
  data.frame(x = c(1, 2, 3)),
  selection = "multiple",
  columnGroups = list(colGroup("group", "x")),
  bordered = TRUE
)
```
![screenshot of table](https://user-images.githubusercontent.com/20401866/85246797-5c0cae00-b411-11ea-94e0-5497d4814efc.png)

**Comment by petbrueck** [comment]
Thanks a lot! I can confirm that this bug has been fixed.
