### ISSUE TITLE
Unexpected interaction between columnGroups and groupBy 

### ISSUE THREAD

**Issue by tdeenes** [glin/reactable#87]
If both `columnGroups` and `groupBy` arguments are provided, the `groupBy` column receives the default column header (see `defaultGroupHeader` in `reactableLang()`).

```r
reactable(
  iris[1:5, ],
  columns = list(
    Sepal.Length = colDef(name = "Length"),
    Sepal.Width = colDef(name = "Width"),
    Petal.Length = colDef(name = "Length"),
    Petal.Width = colDef(name = "Width")
  ),
  columnGroups = list(
    colGroup(name = "Sepal", columns = c("Sepal.Length", "Sepal.Width")),
    colGroup(name = "Petal", columns = c("Petal.Length", "Petal.Width"))
  ),
  groupBy = "Species"
)
```

Is this intentional?

**Comment by glin** [comment]
Yes, this is intentional, and inherited from the underlying React Table library. However, it'll be removed in the next release, along with the `defaultGroupHeader` argument.

For now, there's no way to get rid of that default column group, but you can give it an empty name. To make it look less awkward, you could also use a bordered style:

```r
reactable(
  iris[1:5, ],
  columns = list(
    Sepal.Length = colDef(name = "Length"),
    Sepal.Width = colDef(name = "Width"),
    Petal.Length = colDef(name = "Length"),
    Petal.Width = colDef(name = "Width")
  ),
  columnGroups = list(
    colGroup(name = "", columns = "Species"),
    colGroup(name = "Sepal", columns = c("Sepal.Length", "Sepal.Width")),
    colGroup(name = "Petal", columns = c("Petal.Length", "Petal.Width"))
  ),
  groupBy = "Species",
  bordered = TRUE
)
```
![reactable output](https://user-images.githubusercontent.com/20401866/95666410-db3c0400-0b1e-11eb-9a9e-d1e98aee4967.png)

In the next release, there won't be a column group unless you specifically create one:

![grouped reactable with column groups](https://user-images.githubusercontent.com/20401866/95666804-f446b400-0b22-11eb-954e-f95cfa782492.png)

**Comment by tdeenes** [comment]
@glin , thanks for the quick response (and for the package as well :). What is the ETA of the next release?

**Comment by glin** [comment]
I don't have an ETA yet, and those changes aren't even up on GitHub. But I'll comment here again once it's available in the development version.

**Comment by glin** [comment]
The automatic column grouping is now removed in the development version (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). Since it could be a breaking change in some cases, I've marked it so in the NEWS:


### Breaking changes

* When both `columnGroups` and `groupBy` arguments are provided, `groupBy`  columns are no longer added to a column group automatically  ([#87](https://github.com/glin/reactable/issues/87)).
* The `defaultGroupHeader` argument in `reactableLang()` is now deprecated and  no longer used. Use the `columnGroups` argument in `reactable()` to customize  the column group header for `groupBy` columns.
