### ISSUE TITLE
Default page selection or horizontal scroll direction

### ISSUE THREAD

**Issue by ryanfabricius** [glin/reactable#93]
Hey, is it possible to default the scroll to be from right to left on overflow? If this is not possible, can the default page selection be the last page? 
Appreciate the response!

**Comment by glin** [comment]
Hi, this might be possible, depending on your use case. Do you have a table in a right-to-left language? If so, the table should already scroll from right to left if the page is set in an `rtl` direction. For example, just setting text direction on the table itself:
```r
reactable(MASS::Cars93, style = list(direction = "rtl"))
```
If the table isn't in an RTL language, then this isn't very common. I would suggest reordering columns so that the important ones appear first, or trying to make all columns fit on one screen. Or if it's time series data and you want to show latest first, transposing the table and pre-sorting by a date column instead. If this is a Shiny app, you could also render a subset of columns initially (hiding less important ones through  `colDef(show = FALSE/TRUE)`), then having some way to toggle additional columns to appear.

If there's no better solution, then it is possible to set default scrolling using external JavaScript, but it's more like a hack. You can find the scrollable element of the table and set its `scrollLeft` property to the max value, like:
```r
htmltools::div(
  reactable(
    MASS::Cars93,
    elementId = "my-tbl"
  ),
  htmlwidgets::onStaticRenderComplete("document.querySelector('#my-tbl .rt-table').scrollLeft = Number.MAX_SAFE_INTEGER")
)
```
This relies on an undocumented CSS class (`.rt-table`) though, so it's not guaranteed to work in the future.

A default page selection also isn't supported, but you can programmatically set the page in Shiny using `updateReactable()`: https://glin.github.io/reactable/articles/examples.html#update-a-reactable-instance. A default page option would be simple to add, but I haven't come across any use cases for it. I think a default sort usually handles the case where you want to show certain rows first, so I wonder, would default sorting work for your case?

**Comment by ryanfabricius** [comment]
Thank you for your response! 

It is a very unique, requested use case with columns as observations and three summary columns on the right (sticky columns). The requested position for the most recent observation, was right next to the summary columns. As time went on, the weekly observation columns would overflow and not be seen until scrolled. 

The table was not written in RTL, but thought using RTL was the best way to get the table to overflow to the left to seem "pre-scrolled". Using the RTL fix did solve the problem. However, since using RTL brings additional challenges, I went with the Javascript hack.

I ended up going with the Javascript hack as it was very clean and solved my overflow issues. I will keep the other work arounds in mind as this is not guaranteed to work in the future. 

I appreciate the time you took to respond. The fix has now been implemented.
